#!/usr/bin/env bash
# install/00-base.sh — baseline system prep.
#   - Set hostname from profile
#   - Install baseline apt packages
#   - Ensure user is in dialout/i2c/gpio groups
#   - Create /etc/beatbird/ and copy secrets into place

source "$(dirname "$0")/_lib.sh"

log_step "Baseline packages"
apt-get update -qq
ensure_pkg \
  git make python3 python3-pip python3-venv python3-yaml \
  i2c-tools alsa-utils curl ca-certificates \
  avahi-daemon libnss-mdns \
  jq

log_step "User & groups"
usermod -a -G dialout,i2c,gpio,audio,plugdev "$BEATBIRD_USER"

log_step "Hostname"
HOSTNAME_NEW="$(pq identity.hostname)"
if [[ -n "$HOSTNAME_NEW" && "$HOSTNAME_NEW" != "$(hostname)" ]]; then
  hostnamectl set-hostname "$HOSTNAME_NEW"
  # Update /etc/hosts 127.0.1.1 line
  sed -i "s/^127\.0\.1\.1\s.*/127.0.1.1\t$HOSTNAME_NEW/" /etc/hosts 2>/dev/null || \
    echo "127.0.1.1    $HOSTNAME_NEW" >> /etc/hosts
  log_ok "hostname → $HOSTNAME_NEW"
fi

log_step "/etc/beatbird/"
ensure_etc_beatbird

# Copy secrets from repo secrets/ dir into /etc/beatbird/ (repo dir is NOT
# readable to the bridge user's service — systemd has ProtectHome=read-only).
for s in wifi.pass mqtt.pass; do
  src="$SECRETS_DIR/$s"
  dst="$ETC_DIR/$s"
  if [[ -f "$src" ]]; then
    install -m 600 -o "$BEATBIRD_USER" -g "$BEATBIRD_GROUP" "$src" "$dst"
  elif [[ ! -f "$dst" ]]; then
    log_warn "$src missing — run 'make secrets' and fill it in"
  fi
done

# /etc/beatbird/env  — shell-style env for systemd EnvironmentFile=
MQTT_HOST="$(pq mqtt.host)"
MQTT_PORT="$(pq_or mqtt.port 1883)"
MQTT_USER="$(pq mqtt.user)"
MQTT_PASS="$( [[ -f "$ETC_DIR/mqtt.pass" ]] && cat "$ETC_DIR/mqtt.pass" || echo "" )"
SPEAKER_ID="$(pq identity.speaker_id)"
FRIENDLY_NAME="$(pq identity.friendly_name)"
BASE_TOPIC="$(pq mqtt.base_topic)"

cat > "$ETC_DIR/env" <<EOF
# /etc/beatbird/env — generated by install/00-base.sh (do not edit by hand)
MQTT_BROKER=$MQTT_HOST
MQTT_PORT=$MQTT_PORT
MQTT_USER=$MQTT_USER
MQTT_PASS=$MQTT_PASS
BEATBIRD_SPEAKER_ID=$SPEAKER_ID
BEATBIRD_FRIENDLY_NAME=$FRIENDLY_NAME
BEATBIRD_MQTT_BASE_TOPIC=$BASE_TOPIC
BEATBIRD_PROFILE=$PROFILE_YML
BEATBIRD_REPO=$REPO_DIR
EOF
chmod 640 "$ETC_DIR/env"
chown root:"$BEATBIRD_GROUP" "$ETC_DIR/env"
log_ok "/etc/beatbird/env written"

log_step "Enable I2C + SPI + UART"
# Raspberry Pi specific — these are no-ops on other hardware.
# do_serial 0 is buggy: triggers interactive whiptail in some raspi-config
# versions even with nonint. Use the granular do_serial_hw / do_serial_cons
# variants which are properly non-interactive.
if command -v raspi-config >/dev/null 2>&1; then
  raspi-config nonint do_i2c 0 || true
  raspi-config nonint do_spi 0 || true
  raspi-config nonint do_serial_hw 0 2>/dev/null || true   # enable serial hardware
  raspi-config nonint do_serial_cons 1 2>/dev/null || true # disable serial login shell
fi
