#!/usr/bin/env bash
# install/56-overlay-sudo.sh — sudoers rule for overlay-mode operations.
#
# Beat #1 has had this set up out-of-band for ages; the Zipp Mini 2 didn't,
# which made every deploy iteration require an SSH password prompt for the
# overlayroot-chroot step. We let the bridge user (devusr) run two specific
# commands without a password:
#
#   - /usr/sbin/overlayroot-chroot
#       Required to persist code changes / config edits onto the read-only
#       root layer. Without it, every `git pull` inside chroot triggers a
#       sudo prompt.
#
#   - /usr/bin/systemctl reboot
#       Already in 55-web-sudo.sh, but only when web.enabled=true. We keep
#       a copy here so the rule is present even on profiles that don't run
#       the web UI.
#
# Independent of web.enabled by design — this is about maintenance, not
# end-user controls.

source "$(dirname "$0")/_lib.sh"

log_step "installing sudoers rule for overlay-mode maintenance"

SUDOERS_FILE=/etc/sudoers.d/beatbird-overlay
cat > "$SUDOERS_FILE" <<EOF
# Auto-generated by install/56-overlay-sudo.sh — passwordless commands
# the bridge user needs for overlay-mode persistence + reboot.
$BEATBIRD_USER ALL=(root) NOPASSWD: /usr/sbin/overlayroot-chroot
$BEATBIRD_USER ALL=(root) NOPASSWD: /usr/bin/systemctl reboot
EOF
chmod 0440 "$SUDOERS_FILE"

if ! visudo -cf "$SUDOERS_FILE" >/dev/null; then
  log_err "sudoers file failed validation, removing"
  rm -f "$SUDOERS_FILE"
  exit 1
fi

log_ok "sudoers rule installed at $SUDOERS_FILE"
