// =============================================================================
// theme.h — BeatBird Display Theme System
// =============================================================================
// Central source of truth for the visual language. Everything that has a
// colour, a size, a font, a duration or an opacity lives here. Screens read
// from this header — they never define their own constants.
//
// Accent colour is a runtime variable (Theme::accent) that the Pi pushes via
// `PAL:rrggbb` once after the serial connect handshake. All other tokens are
// compile-time constants tuned for the Nothing-Glyph aesthetic on a round
// 466×466 AMOLED panel.
//
// Font system:
//   When HAS_DEPARTURE_MONO is defined (set via -DHAS_DEPARTURE_MONO=1 in
//   platformio.ini after running fonts/build.py), the display uses
//   pixel-perfect Departure Mono at 11/22/33/44 px. Otherwise it falls back
//   to Montserrat so the firmware always builds.
// =============================================================================
#pragma once

#include <lvgl.h>
#include <stdint.h>

// ─── Departure Mono externs (generated by fonts/build.py) ───────────────────
// These resolve when HAS_DEPARTURE_MONO is enabled in platformio.ini.
#ifdef HAS_DEPARTURE_MONO
extern "C" {
    extern const lv_font_t departure_mono_11;
    extern const lv_font_t departure_mono_22;
    extern const lv_font_t departure_mono_33;
    extern const lv_font_t departure_mono_44;
}
#endif

// ─── Inter externs (generated by fonts/build_inter.py) ──────────────────────
// The "Warm Funktional" grotesk. Resolves when HAS_INTER is set; preferred over
// Departure Mono in the font accessors below.
#ifdef HAS_INTER
extern "C" {
    extern const lv_font_t inter_clock;   // 140 ExtraBold, digits+colon subset
    extern const lv_font_t inter_title;   //  40 ExtraBold, full Latin-1
    extern const lv_font_t inter_lg;      //  30 SemiBold
    extern const lv_font_t inter_md;      //  21 Medium
    extern const lv_font_t inter_sm;      //  14 SemiBold
}
#endif

// ─── Weather Icons font (generated by fonts/build_weather.py) ───────────────
#ifdef HAS_WEATHER_ICONS
extern "C" {
    extern const lv_font_t weather_icons;   // 40 px, 7 weather glyphs
}
namespace Theme { inline const lv_font_t *font_weather() { return &weather_icons; } }
#endif

namespace Theme {

// ─── Display geometry ────────────────────────────────────────────────────────
// All radii are measured from the geometric centre (233, 233). Values are in
// physical pixels. Keep them aligned with the mockup so the firmware matches
// the design preview.

constexpr int CENTER       = 233;   // 466 / 2
constexpr int VOL_RING_R   = 218;   // outer volume dot ring
constexpr int VOL_DOT_R    = 4;     // filled dot radius
constexpr int VOL_DOT_R_DIM = 2;    // unfilled / dim dot radius
constexpr int VOL_DOT_COUNT = 24;   // dots around the ring

constexpr int PROG_RING_R  = 192;   // progress stipple ring
constexpr int PROG_DOT_R   = 1;     // very small — almost a pixel
constexpr int PROG_SEG_COUNT = 60;
constexpr int PROG_ARC_START_DEG = 135;   // bottom-left
constexpr int PROG_ARC_SWEEP_DEG = 270;   // around the bottom

// Note: a sound-print halo at r=225 was tried (Phase-2 spec) and looked
// noisy/overwhelming on the round 466 px panel. Energy modulation now
// lives on the existing vol-ring lit dots and the source marker.

constexpr int SOURCE_MARKER_SIZE = 10;     // square px
constexpr int SOURCE_MARKER_Y    = 9;      // distance from top edge

// Note: the dot-matrix WiFi antenna at (CENTER, 42) was removed in favour of
// CenterStage's "WIFI WEAK" / "PI OFFLINE" announcements — one channel for
// connection state instead of two competing for the same space.

// Text placement (relative to centre). Title / Artist moved further apart
// in the CenterStage redesign — the freed-up middle slot is occupied by
// the priority-chain status label (PAUSE / MUTE / PI OFFLINE / …).
// STATE_ICON_Y and VOLUME_PCT_Y are kept for backward compat but unused
// now that state_icon is permanently hidden and lbl_volume is gone.
constexpr int TITLE_Y_OFFSET     = -43;   // y ≈ 190
constexpr int ARTIST_Y_OFFSET    =  32;   // y ≈ 265
constexpr int STATE_ICON_Y       =  66;   // unused after CenterStage refactor
constexpr int VOLUME_PCT_Y       =  124;  // unused after CenterStage refactor
constexpr int SOURCE_LABEL_Y     = -170;

// ─── Animations & timing ────────────────────────────────────────────────────

constexpr uint32_t ANIM_FADE_MS       = 200;
constexpr uint32_t ANIM_SWEEP_MS      = 350;
constexpr uint32_t ANIM_BOOT_PULSE_MS = 1200;   // status-line breathing
constexpr uint32_t ANIM_BOOT_ARC_MS   = 1800;   // outer ring rotation
constexpr uint32_t STANDBY_AFTER_MS   = 5 * 60 * 1000;   // 5 min idle
constexpr uint32_t DIM_AFTER_MS       = 30 * 1000;       // 30 s idle dims display
constexpr uint32_t ACTION_TOAST_MS    = 1200;
constexpr uint32_t LONG_PRESS_MS      = 1500;
constexpr uint8_t  DIM_BRIGHTNESS     = 140;
constexpr uint8_t  FULL_BRIGHTNESS    = 255;

// ─── Colour palette (compile-time constants) ────────────────────────────────
// All colours are RGB565-safe on the SH8601. The accent is set at runtime
// from the profile via the PAL: serial command.

namespace Color {
    // Backgrounds — pure black for AMOLED pixels-off
    constexpr lv_color_t BG           = LV_COLOR_MAKE(0x00, 0x00, 0x00);
    constexpr lv_color_t BG_DIM       = LV_COLOR_MAKE(0x0F, 0x0F, 0x0F);
    constexpr lv_color_t BG_DEEP      = LV_COLOR_MAKE(0x16, 0x16, 0x16);

    // Foregrounds — neutral hierarchy
    constexpr lv_color_t TEXT_BODY    = LV_COLOR_MAKE(0x9a, 0x9a, 0x9a);
    constexpr lv_color_t TEXT_DIM     = LV_COLOR_MAKE(0x5a, 0x5a, 0x5a);
    constexpr lv_color_t TEXT_FAINT   = LV_COLOR_MAKE(0x2e, 0x2e, 0x2e);

    // Source markers (small dot only)
    constexpr lv_color_t SRC_SPOTIFY  = LV_COLOR_MAKE(0x1E, 0xD7, 0x60);
    constexpr lv_color_t SRC_BT       = LV_COLOR_MAKE(0x3F, 0x8C, 0xFF);
    constexpr lv_color_t SRC_TOSLINK  = LV_COLOR_MAKE(0xFF, 0x95, 0x00);
    constexpr lv_color_t SRC_SNAPCAST = LV_COLOR_MAKE(0xA6, 0x78, 0xFF);
    constexpr lv_color_t SRC_NONE     = LV_COLOR_MAKE(0x3a, 0x3a, 0x3a);

    // Defaults — every runtime palette slot has a compile-time fallback so
    // the firmware always boots with sensible colours even before the Pi
    // pushes a PAL: line.
    constexpr lv_color_t ACCENT_DEFAULT         = LV_COLOR_MAKE(0xF0, 0xCB, 0x7B);  // champagne gold
    constexpr lv_color_t ACCENT_GLOW_DEFAULT    = LV_COLOR_MAKE(0xFF, 0xE6, 0xB3);  // brighter champagne
    constexpr lv_color_t ACCENT_DIM_DEFAULT     = LV_COLOR_MAKE(0x3c, 0x32, 0x1e);  // ~25% of accent on black
    constexpr lv_color_t TEXT_PRIMARY_DEFAULT   = LV_COLOR_MAKE(0xF4, 0xEF, 0xE0);  // cream
    constexpr lv_color_t TEXT_SECONDARY_DEFAULT = LV_COLOR_MAKE(0xA8, 0x9E, 0x89);  // linen
    constexpr lv_color_t ACCENT_ALERT_DEFAULT   = LV_COLOR_MAKE(0xC7, 0x3E, 0x2C);  // rust

    // Legacy alias for code that still references this name. Now lives as
    // a runtime variable (Theme::accent_alert) too.
    constexpr lv_color_t ACCENT_ALERT           = ACCENT_ALERT_DEFAULT;
}

// ─── Runtime palette (set by the extended PAL: command from the Pi) ─────────
// All six tokens above are mirrored as runtime variables. The bridge pushes
// the per-speaker palette once after serial connect:
//     PAL:a=2D6A4F|g=52B788|d=1B4332|p=F4EFE0|s=A89E89|e=C73E2C
// Legacy `PAL:2D6A4F` (single accent, no key=value) is still accepted and
// only sets `accent`; the other slots stay at their defaults.

extern lv_color_t accent;           // primary highlight (e.g. forest mid)
extern lv_color_t accent_glow;      // brighter variant (e.g. sage glow)
extern lv_color_t accent_dim;       // ~25% accent on black — derived if not pushed
extern lv_color_t text_primary;     // body / title text (e.g. cream)
extern lv_color_t text_secondary;   // labels / sublines (e.g. linen)
extern lv_color_t accent_alert;     // warnings / errors  (e.g. rust)

/** Apply a new accent colour. Called by the protocol layer when a legacy
 *  PAL:<hex> line arrives. Recomputes accent_dim and triggers a refresh.
 *  Other palette slots are left untouched. */
void set_accent(uint8_t r, uint8_t g, uint8_t b);

/** Parse a 6-char hex string (no leading #) and apply as accent. */
bool set_accent_hex(const char *hex6);

/** Apply one specific palette slot by name char ('a'/'g'/'d'/'p'/'s'/'e').
 *  Returns true if the slot was recognised. Used by the new PAL: parser
 *  while iterating over key=value fields. */
bool set_palette_slot_hex(char slot, const char *hex6);

// ─── Fonts ──────────────────────────────────────────────────────────────────
// Sizes are 11 px multiples for pixel-perfect rendering of Departure Mono.
// Fallback to Montserrat at the closest available size keeps the build green
// when the .c files haven't been generated yet (see fonts/build.py).
//
//   display_lg  = 33 px   — large titles, boot status, action toasts
//   display_md  = 22 px   — track artist, source label, body display
//   body        = 11 px   — labels, status rows, sublines
//   label       = 11 px   — alias for body, used in semantic contexts
//   clock       = 44 px   — standby clock face

// Warm-Funktional explicit type scale: font_clock_xl / title / lg / md / sm.
// Back-compat accessors (font_display_lg/md, font_body/label, font_clock) are
// kept so boot/settings/center_stage keep working — they map onto the same
// faces. Every backend defines the full set so any screen compiles.

#if defined(HAS_INTER)

inline const lv_font_t *font_clock_xl()   { return &inter_clock; }   // 140
inline const lv_font_t *font_title()      { return &inter_title; }   //  40
inline const lv_font_t *font_lg()         { return &inter_lg; }      //  30
inline const lv_font_t *font_md()         { return &inter_md; }      //  21
inline const lv_font_t *font_sm()         { return &inter_sm; }      //  14
inline const lv_font_t *font_display_lg() { return &inter_lg; }
inline const lv_font_t *font_display_md() { return &inter_md; }
inline const lv_font_t *font_body()       { return &inter_sm; }
inline const lv_font_t *font_label()      { return &inter_sm; }
inline const lv_font_t *font_clock()      { return &inter_clock; }

// Inter is proportional — no faux-mono tracking. Tracked labels set their own
// letter_space inline where the design calls for it.
constexpr int LETTER_SPACE_DISPLAY = 0;
constexpr int LETTER_SPACE_LABEL   = 1;
constexpr int LETTER_SPACE_BODY    = 0;

#elif defined(HAS_DEPARTURE_MONO)

inline const lv_font_t *font_clock_xl()   { return &departure_mono_44; }
inline const lv_font_t *font_title()      { return &departure_mono_33; }
inline const lv_font_t *font_lg()         { return &departure_mono_33; }
inline const lv_font_t *font_md()         { return &departure_mono_22; }
inline const lv_font_t *font_sm()         { return &departure_mono_11; }
inline const lv_font_t *font_display_lg() { return &departure_mono_33; }
inline const lv_font_t *font_display_md() { return &departure_mono_22; }
inline const lv_font_t *font_body()       { return &departure_mono_11; }
inline const lv_font_t *font_label()      { return &departure_mono_11; }
inline const lv_font_t *font_clock()      { return &departure_mono_44; }

// Departure Mono is already wide-spaced internally; small letter-space gain
// just for the very large display sizes.
constexpr int LETTER_SPACE_DISPLAY = 1;
constexpr int LETTER_SPACE_LABEL   = 1;
constexpr int LETTER_SPACE_BODY    = 0;

#else   // Montserrat fallback

inline const lv_font_t *font_clock_xl()   { return &lv_font_montserrat_48; }
inline const lv_font_t *font_title()      { return &lv_font_montserrat_32; }
inline const lv_font_t *font_lg()         { return &lv_font_montserrat_32; }
inline const lv_font_t *font_md()         { return &lv_font_montserrat_24; }
inline const lv_font_t *font_sm()         { return &lv_font_montserrat_14; }
inline const lv_font_t *font_display_lg() { return &lv_font_montserrat_32; }
inline const lv_font_t *font_display_md() { return &lv_font_montserrat_24; }
inline const lv_font_t *font_body()       { return &lv_font_montserrat_14; }
inline const lv_font_t *font_label()      { return &lv_font_montserrat_14; }
inline const lv_font_t *font_clock()      { return &lv_font_montserrat_48; }

// Montserrat (rounded geometric sans) needs more tracking to read as mono-ish.
constexpr int LETTER_SPACE_DISPLAY = 3;
constexpr int LETTER_SPACE_LABEL   = 4;
constexpr int LETTER_SPACE_BODY    = 2;

#endif

}  // namespace Theme
