// =============================================================================
// theme.h — BeatBird Display Theme System
// =============================================================================
// Central source of truth for the visual language. Everything that has a
// colour, a size, a font, a duration or an opacity lives here. Screens read
// from this header — they never define their own constants.
//
// Accent colour is a runtime variable (Theme::accent) that the Pi pushes via
// `PAL:rrggbb` once after the serial connect handshake. All other tokens are
// compile-time constants tuned for the Nothing-Glyph aesthetic on a round
// 466×466 AMOLED panel.
//
// Font system:
//   When HAS_DEPARTURE_MONO is defined (set via -DHAS_DEPARTURE_MONO=1 in
//   platformio.ini after running fonts/build.py), the display uses
//   pixel-perfect Departure Mono at 11/22/33/44 px. Otherwise it falls back
//   to Montserrat so the firmware always builds.
// =============================================================================
#pragma once

#include <lvgl.h>
#include <stdint.h>

// ─── Departure Mono externs (generated by fonts/build.py) ───────────────────
// These resolve when HAS_DEPARTURE_MONO is enabled in platformio.ini.
#ifdef HAS_DEPARTURE_MONO
extern "C" {
    extern const lv_font_t departure_mono_11;
    extern const lv_font_t departure_mono_22;
    extern const lv_font_t departure_mono_33;
    extern const lv_font_t departure_mono_44;
}
#endif

namespace Theme {

// ─── Display geometry ────────────────────────────────────────────────────────
// All radii are measured from the geometric centre (233, 233). Values are in
// physical pixels. Keep them aligned with the mockup so the firmware matches
// the design preview.

constexpr int CENTER       = 233;   // 466 / 2
constexpr int VOL_RING_R   = 218;   // outer volume dot ring
constexpr int VOL_DOT_R    = 4;     // filled dot radius
constexpr int VOL_DOT_R_DIM = 2;    // unfilled / dim dot radius
constexpr int VOL_DOT_COUNT = 24;   // dots around the ring

constexpr int PROG_RING_R  = 192;   // progress stipple ring
constexpr int PROG_DOT_R   = 1;     // very small — almost a pixel
constexpr int PROG_SEG_COUNT = 60;
constexpr int PROG_ARC_START_DEG = 135;   // bottom-left
constexpr int PROG_ARC_SWEEP_DEG = 270;   // around the bottom

// Note: a sound-print halo at r=225 was tried (Phase-2 spec) and looked
// noisy/overwhelming on the round 466 px panel. Energy modulation now
// lives on the existing vol-ring lit dots and the source marker.

constexpr int SOURCE_MARKER_SIZE = 10;     // square px
constexpr int SOURCE_MARKER_Y    = 9;      // distance from top edge

// WiFi signal indicator — dot-matrix "antenna" centered under the source
// marker. Three upward-curving rows of dots that REVEAL with signal
// strength (no dim placeholder dots — keeps the area clean).
//
//   Level 0 (no signal):  dim base dot only
//   Level 1 (≥ -85 dBm):  bright base dot
//   Level 2 (≥ -75 dBm):  + inner arc  (3 dots)
//   Level 3 (≥ -67 dBm):  + middle arc (5 dots)
//   Level 4 (≥ -55 dBm):  + outer arc  (7 dots)
//
// Lives in the gap between the source marker (y ≤ 19) and the source
// label (y ≈ 63). Dot radius scaled up from 2→3 px for arm's-length
// visibility; arc radii bumped to keep proportions.
constexpr int WIFI_CX           = CENTER;
constexpr int WIFI_CY           = 42;    // y of the base dot
constexpr int WIFI_DOT_R        = 3;
constexpr int WIFI_ARC_DOT_R    = 3;
constexpr int WIFI_ARC1_R       = 8;
constexpr int WIFI_ARC2_R       = 14;
constexpr int WIFI_ARC3_R       = 20;
constexpr int WIFI_ARC1_DOTS    = 3;
constexpr int WIFI_ARC2_DOTS    = 5;
constexpr int WIFI_ARC3_DOTS    = 7;
constexpr int WIFI_ARC_SPAN_DEG = 90;    // upward-opening 90° sweep

// Text placement (relative to centre). Title / Artist moved further apart
// in the CenterStage redesign — the freed-up middle slot is occupied by
// the priority-chain status label (PAUSE / MUTE / PI OFFLINE / …).
// STATE_ICON_Y and VOLUME_PCT_Y are kept for backward compat but unused
// now that state_icon is permanently hidden and lbl_volume is gone.
constexpr int TITLE_Y_OFFSET     = -43;   // y ≈ 190
constexpr int ARTIST_Y_OFFSET    =  32;   // y ≈ 265
constexpr int STATE_ICON_Y       =  66;   // unused after CenterStage refactor
constexpr int VOLUME_PCT_Y       =  124;  // unused after CenterStage refactor
constexpr int SOURCE_LABEL_Y     = -170;

// ─── Animations & timing ────────────────────────────────────────────────────

constexpr uint32_t ANIM_FADE_MS       = 200;
constexpr uint32_t ANIM_SWEEP_MS      = 350;
constexpr uint32_t ANIM_BOOT_PULSE_MS = 1200;   // status-line breathing
constexpr uint32_t ANIM_BOOT_ARC_MS   = 1800;   // outer ring rotation
constexpr uint32_t STANDBY_AFTER_MS   = 5 * 60 * 1000;   // 5 min idle
constexpr uint32_t DIM_AFTER_MS       = 30 * 1000;       // 30 s idle dims display
constexpr uint32_t ACTION_TOAST_MS    = 1200;
constexpr uint32_t LONG_PRESS_MS      = 1500;
constexpr uint8_t  DIM_BRIGHTNESS     = 140;
constexpr uint8_t  FULL_BRIGHTNESS    = 255;

// ─── Colour palette (compile-time constants) ────────────────────────────────
// All colours are RGB565-safe on the SH8601. The accent is set at runtime
// from the profile via the PAL: serial command.

namespace Color {
    // Backgrounds — pure black for AMOLED pixels-off
    constexpr lv_color_t BG           = LV_COLOR_MAKE(0x00, 0x00, 0x00);
    constexpr lv_color_t BG_DIM       = LV_COLOR_MAKE(0x0F, 0x0F, 0x0F);
    constexpr lv_color_t BG_DEEP      = LV_COLOR_MAKE(0x16, 0x16, 0x16);

    // Foregrounds — neutral hierarchy
    constexpr lv_color_t TEXT_BODY    = LV_COLOR_MAKE(0x9a, 0x9a, 0x9a);
    constexpr lv_color_t TEXT_DIM     = LV_COLOR_MAKE(0x5a, 0x5a, 0x5a);
    constexpr lv_color_t TEXT_FAINT   = LV_COLOR_MAKE(0x2e, 0x2e, 0x2e);

    // Source markers (small dot only)
    constexpr lv_color_t SRC_SPOTIFY  = LV_COLOR_MAKE(0x1E, 0xD7, 0x60);
    constexpr lv_color_t SRC_BT       = LV_COLOR_MAKE(0x3F, 0x8C, 0xFF);
    constexpr lv_color_t SRC_TOSLINK  = LV_COLOR_MAKE(0xFF, 0x95, 0x00);
    constexpr lv_color_t SRC_SNAPCAST = LV_COLOR_MAKE(0xA6, 0x78, 0xFF);
    constexpr lv_color_t SRC_NONE     = LV_COLOR_MAKE(0x3a, 0x3a, 0x3a);

    // Defaults — overridden at runtime by PAL: command
    // Champagne gold — tuned for Zipp Mini 2 turquoise/cream enclosure
    constexpr lv_color_t ACCENT_DEFAULT = LV_COLOR_MAKE(0xF0, 0xCB, 0x7B);

    // Center-stage alert color — for "PI OFFLINE" / "ERROR" announcements.
    // Compile-time constant for now; future runtime palette will replace this.
    constexpr lv_color_t ACCENT_ALERT   = LV_COLOR_MAKE(0xC7, 0x3E, 0x2C);
}

// ─── Runtime accent (set by PAL: command from Pi) ───────────────────────────

extern lv_color_t accent;
extern lv_color_t accent_dim;   // ~25% accent on black, for unfilled segments

/** Apply a new accent colour. Called by the protocol layer when a PAL: line
 *  arrives. Recomputes derived shades and triggers a global UI refresh. */
void set_accent(uint8_t r, uint8_t g, uint8_t b);

/** Parse a 6-char hex string (no leading #) and apply. Returns true on success. */
bool set_accent_hex(const char *hex6);

// ─── Fonts ──────────────────────────────────────────────────────────────────
// Sizes are 11 px multiples for pixel-perfect rendering of Departure Mono.
// Fallback to Montserrat at the closest available size keeps the build green
// when the .c files haven't been generated yet (see fonts/build.py).
//
//   display_lg  = 33 px   — large titles, boot status, action toasts
//   display_md  = 22 px   — track artist, source label, body display
//   body        = 11 px   — labels, status rows, sublines
//   label       = 11 px   — alias for body, used in semantic contexts
//   clock       = 44 px   — standby clock face

#ifdef HAS_DEPARTURE_MONO

inline const lv_font_t *font_display_lg() { return &departure_mono_33; }
inline const lv_font_t *font_display_md() { return &departure_mono_22; }
inline const lv_font_t *font_body()       { return &departure_mono_11; }
inline const lv_font_t *font_label()      { return &departure_mono_11; }
inline const lv_font_t *font_clock()      { return &departure_mono_44; }

// Departure Mono is already wide-spaced internally; small letter-space gain
// just for the very large display sizes.
constexpr int LETTER_SPACE_DISPLAY = 1;
constexpr int LETTER_SPACE_LABEL   = 1;
constexpr int LETTER_SPACE_BODY    = 0;

#else   // Montserrat fallback

inline const lv_font_t *font_display_lg() { return &lv_font_montserrat_32; }
inline const lv_font_t *font_display_md() { return &lv_font_montserrat_24; }
inline const lv_font_t *font_body()       { return &lv_font_montserrat_14; }
inline const lv_font_t *font_label()      { return &lv_font_montserrat_14; }
inline const lv_font_t *font_clock()      { return &lv_font_montserrat_48; }

// Montserrat (rounded geometric sans) needs more tracking to read as mono-ish.
constexpr int LETTER_SPACE_DISPLAY = 3;
constexpr int LETTER_SPACE_LABEL   = 4;
constexpr int LETTER_SPACE_BODY    = 2;

#endif

}  // namespace Theme
